// pb-auth — puts a PartsBase dashboard behind corporate sign-in.
//
// Generated by the /protect-dashboard command. There is no need to edit this by
// hand: to change anything, run the command again.
//
// Runs on Netlify's edge (Deno). No dependencies, and it holds no secret — it only
// verifies signatures against the broker's public key.

// ─── configuration, written by the command ───────────────────────────────────
const BROKER = 'https://pb-auth.netlify.app';
const REQUIRED_GROUPS = []; // e.g. ['Finance', 'Operations'] — group titles, as written in AD
// ─────────────────────────────────────────────────────────────────────────────

const COOKIE = 'pb_session';
const LOGOUT_PATH = '/pb-auth/logout';
const JWKS_TTL_MS = 60 * 60 * 1000;
const SESSION_MAX_AGE = 7 * 24 * 60 * 60;

let jwksCache = { keys: [], fetchedAt: 0, loaded: false };

export function _resetJwksCache() {
  jwksCache = { keys: [], fetchedAt: 0, loaded: false };
}

function b64urlToBytes(s) {
  const b64 = s.replace(/-/g, '+').replace(/_/g, '/');
  const pad = b64.length % 4 === 0 ? '' : '='.repeat(4 - (b64.length % 4));
  const bin = atob(b64 + pad);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function b64urlToJson(s) {
  return JSON.parse(new TextDecoder().decode(b64urlToBytes(s)));
}

function readCookie(header, name) {
  if (!header) return null;
  for (const part of header.split(';')) {
    const t = part.trim();
    const eq = t.indexOf('=');
    if (eq < 1) continue;
    if (t.slice(0, eq) === name) return t.slice(eq + 1);
  }
  return null;
}

async function loadJwks(fetchImpl, now) {
  const res = await fetchImpl(`${BROKER}/.well-known/jwks.json`);
  if (!res.ok) throw new Error(`jwks ${res.status}`);
  const body = await res.json();
  jwksCache = { keys: body.keys ?? [], fetchedAt: now, loaded: true };
  return jwksCache.keys;
}

async function keyFor(kid, fetchImpl, now) {
  const fresh = jwksCache.loaded && now - jwksCache.fetchedAt < JWKS_TTL_MS;
  const keys = fresh ? jwksCache.keys : await loadJwks(fetchImpl, now);
  let jwk = keys.find((k) => k.kid === kid);
  // Unknown kid on a warm cache means the broker rotated its key. Refetch once.
  if (!jwk && fresh) jwk = (await loadJwks(fetchImpl, now)).find((k) => k.kid === kid);
  if (!jwk) return null;
  return crypto.subtle.importKey(
    'jwk',
    { kty: jwk.kty, crv: jwk.crv, x: jwk.x, y: jwk.y, ext: true },
    { name: 'ECDSA', namedCurve: 'P-256' },
    false,
    ['verify']
  );
}

/**
 * Verify a session token issued by the broker.
 * Returns the claims, or null if the token is unusable for any reason.
 * Never throws: every failure is a rejection.
 */
export async function verifySession(token, origin, { fetchImpl = fetch, now = Date.now() } = {}) {
  try {
    const parts = String(token).split('.');
    if (parts.length !== 3) return null;
    const [h, p, s] = parts;

    const header = b64urlToJson(h);
    if (!header || typeof header !== 'object') return null;
    if (header.alg !== 'ES256') return null;

    const key = await keyFor(header.kid, fetchImpl, now);
    if (!key) return null;

    const ok = await crypto.subtle.verify(
      { name: 'ECDSA', hash: 'SHA-256' },
      key,
      b64urlToBytes(s),
      new TextEncoder().encode(`${h}.${p}`)
    );
    if (!ok) return null;

    const claims = b64urlToJson(p);
    if (!claims || typeof claims !== 'object') return null;
    if (claims.pb_typ !== 'session') return null;
    if (claims.iss !== BROKER) return null;
    if (claims.aud !== origin) return null;

    const secs = Math.floor(now / 1000);
    if (typeof claims.exp !== 'number' || claims.exp + 60 < secs) return null;
    if (claims.nbf !== undefined && (typeof claims.nbf !== 'number' || claims.nbf - 60 > secs)) return null;

    return claims;
  } catch {
    return null;
  }
}

/**
 * Decide whether these claims satisfy the configured group filter.
 * Returns null when they do, or a reason when they do not.
 */
export function checkGroups(claims, groups = REQUIRED_GROUPS) {
  if (!groups || groups.length === 0) return null;
  // The broker resolves the user's memberships against Entra at every sign-in and
  // puts the group titles here, so a group changed in AD takes effect on the next
  // sign-in with no catalogue to keep in sync.
  if (claims.groups_resolved !== true) return 'unresolved';
  const held = new Set((claims.group_names ?? []).map((n) => String(n).trim().toLowerCase()));
  return groups.some((g) => held.has(String(g).trim().toLowerCase())) ? null : 'not_in_group';
}

function page(status, title, message) {
  return new Response(
    `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title>
<style>body{font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;margin:0;
display:grid;place-items:center;min-height:100vh;background:#f6f7f9;color:#14181f}
main{max-width:34rem;padding:2rem;text-align:center}h1{font-size:1.3rem;margin:0 0 .75rem}
p{margin:0;color:#5d6675}</style></head><body><main>
<h1>${title}</h1><p>${message}</p></main></body></html>`,
    { status, headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' } }
  );
}

const sessionCookie = (value) =>
  `${COOKIE}=${value}; Max-Age=${SESSION_MAX_AGE}; Path=/; HttpOnly; Secure; SameSite=Lax`;
const clearedCookie = () =>
  `${COOKIE}=; Max-Age=0; Path=/; HttpOnly; Secure; SameSite=Lax`;

export async function handleRequest(request, context, deps = {}) {
  const fetchImpl = deps.fetchImpl ?? fetch;
  const now = deps.now ?? Date.now();
  const groups = deps.groups ?? REQUIRED_GROUPS;
  const next = deps.next ?? (() => context.next());

  const url = new URL(request.url);
  const origin = url.origin;

  // Sign out
  if (url.pathname === LOGOUT_PATH) {
    return new Response(null, {
      status: 302,
      headers: { location: `${BROKER}/logout`, 'set-cookie': clearedCookie(), 'cache-control': 'no-store' },
    });
  }

  // Back from the broker with a handoff: redeem it server-to-server.
  const handoff = url.searchParams.get('pb_handoff');
  if (handoff) {
    let session = null;
    try {
      const res = await fetchImpl(`${BROKER}/session`, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ handoff }),
      });
      if (res.ok) session = (await res.json()).session ?? null;
    } catch {
      session = null;
    }
    // Verify what we are about to store, before storing it. Without this a handoff
    // minted for a different dashboard would be exchanged, cached as our cookie, and
    // then fail verification on the next request -- a redirect loop the visitor
    // cannot escape. The broker no longer keeps an allowlist, so this is the check
    // that keeps one dashboard's session out of another dashboard's cookie jar.
    if (session && !(await verifySession(session, origin, { fetchImpl, now }))) {
      session = null;
    }
    // On failure show an error rather than bouncing back to the broker: that loops.
    if (!session) {
      return page(403, 'We could not sign you in',
        'Close this tab and open the dashboard again. If it keeps happening, contact Infrastructure.');
    }
    const clean = new URL(url);
    clean.searchParams.delete('pb_handoff');
    return new Response(null, {
      status: 302,
      headers: {
        location: clean.pathname + clean.search + clean.hash,
        'set-cookie': sessionCookie(session),
        'cache-control': 'no-store',
      },
    });
  }

  // Already signed in?
  const cookie = readCookie(request.headers.get('cookie'), COOKIE);
  if (cookie) {
    const claims = await verifySession(cookie, origin, { fetchImpl, now });
    if (claims) {
      const reason = checkGroups(claims, groups);
      if (reason === 'unresolved') {
        return page(403, 'We could not check your access',
          'We could not confirm which groups you belong to. Try again in a minute; if it persists, contact Infrastructure.');
      }
      if (reason === 'not_in_group') {
        const names = groups.join(', ');
        return page(403, 'You do not have access to this dashboard',
          `This dashboard is limited to: ${names}. If you should have access, ask to be added to the group.`);
      }
      return next();
    }
    // Invalid or expired cookie: clear it and send them to sign in again.
    return new Response(null, {
      status: 302,
      headers: {
        location: `${BROKER}/start?return_to=${encodeURIComponent(url.toString())}`,
        'set-cookie': clearedCookie(),
        'cache-control': 'no-store',
      },
    });
  }

  // No session: to the broker.
  return new Response(null, {
    status: 302,
    headers: {
      location: `${BROKER}/start?return_to=${encodeURIComponent(url.toString())}`,
      'cache-control': 'no-store',
    },
  });
}

export default (request, context) => handleRequest(request, context);
export const config = { path: '/*' };
